package ventanas;


import ConexionBD.BD;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class EditEstudiante extends javax.swing.JFrame {
File f = null;
    String path = null;
    private ImageIcon format = null;
       Icon message= new ImageIcon(getClass().getResource("/Resources/message.png"));
           Icon success = new ImageIcon(getClass().getResource("/Resources/ok1.png"));

   BD con;
    ResultSet result;
        
    public EditEstudiante(Map<String, String> data) {
        initComponents();
          con= new BD();
        con.Conectar();
         String pass= data.get("Key");
     try{
     result= con.ConsultaEstud(pass);
     while(result.next()){
         usuarioE.setText(result.getString("U_Nbre"));
         NombreE.setText(result.getString("E_Nbre"));
        ApellidoE.setText(result.getString("E_Apell"));
        dniE.setText(result.getString("E_DNI"));
        telefonoE.setText(result.getString("E_Tel"));
        emailE.setText(result.getString("E_Email"));
        imagePath.setText(result.getString("E_Foto"));
        comboBoxCursoE.setSelectedItem(result.getString("E_Curso"));
        tutorNE.setText(result.getString("E_NbreTutor"));
        tutorAE.setText(result.getString("E_ApellTutor"));
        passwordE.setText(result.getString("U_Key"));
     }
     }catch(SQLException ex){
         System.out.println(ex);
     }
        imagePath.setVisible(false);
        String imgpath=imagePath.getText();
        setFoto(imgpath);
        setLocationRelativeTo(null);
        
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        usuarioE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        passwordE = new javax.swing.JTextField();
        mostrarNombre = new javax.swing.JLabel();
        mostrarApellido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreE = new javax.swing.JTextField();
        ApellidoE = new javax.swing.JTextField();
        dniE = new javax.swing.JTextField();
        emailE = new javax.swing.JTextField();
        telefonoE = new javax.swing.JTextField();
        tutorNE = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboBoxCursoE = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tutorAE = new javax.swing.JTextField();
        labelImage = new javax.swing.JLabel();
        imagePath = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escuela N ° 178 ");
        setIconImage(new ImageIcon(getClass().getResource("/Resources/e1.jpg")).getImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nombre de usuario: ");

        usuarioE.setEditable(false);
        usuarioE.setBackground(new java.awt.Color(255, 255, 255));
        usuarioE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        usuarioE.setForeground(new java.awt.Color(20, 107, 109));
        usuarioE.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Contraseña");

        passwordE.setEditable(false);
        passwordE.setBackground(new java.awt.Color(255, 255, 255));
        passwordE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        passwordE.setForeground(new java.awt.Color(20, 107, 109));
        passwordE.setBorder(null);

        mostrarNombre.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        mostrarNombre.setForeground(new java.awt.Color(102, 102, 102));
        mostrarNombre.setText("Nombre :");

        mostrarApellido.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        mostrarApellido.setForeground(new java.awt.Color(102, 102, 102));
        mostrarApellido.setText("Apellido:");
        mostrarApellido.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("D.N.I:");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Correo electrónico:");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Teléfono de contacto:");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Curso:");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Nombre del Tutor:");

        NombreE.setEditable(false);
        NombreE.setBackground(new java.awt.Color(255, 255, 255));
        NombreE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        NombreE.setForeground(new java.awt.Color(20, 107, 109));
        NombreE.setBorder(null);

        ApellidoE.setEditable(false);
        ApellidoE.setBackground(new java.awt.Color(255, 255, 255));
        ApellidoE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ApellidoE.setForeground(new java.awt.Color(20, 107, 109));
        ApellidoE.setBorder(null);

        dniE.setEditable(false);
        dniE.setBackground(new java.awt.Color(255, 255, 255));
        dniE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        dniE.setForeground(new java.awt.Color(20, 107, 109));
        dniE.setBorder(null);
        dniE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniEActionPerformed(evt);
            }
        });

        emailE.setBackground(new java.awt.Color(255, 255, 255));
        emailE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        emailE.setForeground(new java.awt.Color(20, 107, 109));
        emailE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 199, 199), 2, true));

        telefonoE.setBackground(new java.awt.Color(255, 255, 255));
        telefonoE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        telefonoE.setForeground(new java.awt.Color(20, 107, 109));
        telefonoE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 199, 199), 2, true));
        telefonoE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                telefonoEMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                telefonoEMousePressed(evt);
            }
        });

        tutorNE.setEditable(false);
        tutorNE.setBackground(new java.awt.Color(255, 255, 255));
        tutorNE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tutorNE.setForeground(new java.awt.Color(20, 107, 109));
        tutorNE.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Editar Datos Personales del Estudiante");

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setForeground(new java.awt.Color(255, 204, 204));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cap-studente.png"))); // NOI18N

        comboBoxCursoE.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxCursoE.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        comboBoxCursoE.setForeground(new java.awt.Color(20, 107, 109));
        comboBoxCursoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "201", "202", "203" }));
        comboBoxCursoE.setBorder(null);
        comboBoxCursoE.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Apellido del Tutor:");

        tutorAE.setEditable(false);
        tutorAE.setBackground(new java.awt.Color(255, 255, 255));
        tutorAE.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tutorAE.setForeground(new java.awt.Color(20, 107, 109));
        tutorAE.setBorder(null);

        labelImage.setBackground(new java.awt.Color(204, 204, 0));
        labelImage.setText("Foto");
        labelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jButton5.setBackground(new java.awt.Color(0, 122, 122));
        jButton5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok1.png"))); // NOI18N
        jButton5.setText("Guardar Cambios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9))
                            .addComponent(jLabel10))
                        .addContainerGap(75, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(mostrarApellido)
                                    .addComponent(mostrarNombre)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuarioE)
                                    .addComponent(passwordE)
                                    .addComponent(NombreE)
                                    .addComponent(ApellidoE)
                                    .addComponent(dniE)
                                    .addComponent(telefonoE)
                                    .addComponent(emailE)
                                    .addComponent(comboBoxCursoE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tutorNE)
                                    .addComponent(tutorAE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(usuarioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel7))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(passwordE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mostrarNombre)
                                    .addComponent(NombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mostrarApellido)
                                    .addComponent(ApellidoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(dniE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(telefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(emailE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(comboBoxCursoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tutorNE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(tutorAE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(imagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(229, 241, 241));

        jButton1.setBackground(new java.awt.Color(229, 241, 241));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/estud.png"))); // NOI18N
        jButton1.setText("Perfil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 175, 175));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        jButton2.setText("Modificar perfil");

        jButton3.setBackground(new java.awt.Color(229, 241, 241));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lupa.png"))); // NOI18N
        jButton3.setText("Consultas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 175, 175));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/salir.png"))); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniEActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          JOptionPane.showMessageDialog(null, "Has cerrado sesión.",
                    "¡Vuelve pronto!", JOptionPane.INFORMATION_MESSAGE, message);
        VentanaInicio vi = new VentanaInicio();
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String e_contrasenia =passwordE.getText();
        String e_curso= (String) comboBoxCursoE.getSelectedItem();
        String e_dni= dniE.getText();
   
        Map<String, String> dataC= new HashMap<>();
                   dataC.put("Key", e_contrasenia); 
                   dataC.put("e_curso", e_curso);
                   dataC.put("dni", e_dni);
        
        ConsultasEstudiante ce= new ConsultasEstudiante(dataC);
        ce.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void telefonoEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoEMouseEntered
       telefonoE.setBackground(new java.awt.Color(255, 255, 255));
       emailE.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_telefonoEMouseEntered

    private void telefonoEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoEMousePressed
          telefonoE.setBackground(new java.awt.Color(255, 255, 255));
       emailE.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_telefonoEMousePressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
   
           
        con.ActualizaEstudiante(passwordE.getText(), emailE.getText(), telefonoE.getText());
        JOptionPane.showMessageDialog(rootPane, "Alumno modificado exitosamente",
                "Registro exitoso", JOptionPane.PLAIN_MESSAGE, success);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String contr= passwordE.getText();
       
               Map<String, String> data= new HashMap<>();

        data.put("Key", contr);
        HomeEstudLogin l= new HomeEstudLogin(data);
       l.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

   
public void setNombre(String n){
    NombreE.setText(n);
}
public void setApellido(String a){
    ApellidoE.setText(a);
}
 public void setNombreUsuario(String user){
            usuarioE.setText(user);
        }
        public void setPassword(String pass){
            passwordE.setText(pass);
        }
     
        public void setDni(String d){
            dniE.setText(d);
        }
        public void setTelef(String tel){
            telefonoE.setText(tel);
        }
        public void setEmail(String correo){
            emailE.setText(correo);
        }
        public void setFoto(String imgPath){
       
            imagePath.setText(imgPath);
            ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(labelImage.getWidth(), labelImage.getHeight(),Image.SCALE_SMOOTH);
        labelImage.setIcon(new ImageIcon(newImage));
        labelImage.setText("");
        }

      
        public void setCurso(String c){
            comboBoxCursoE.setSelectedItem(c);
        }
        public void setTutorNbre(String t_n){
            tutorNE.setText(t_n);
        }
        public void setTutorAp(String t_a){
            tutorAE.setText(t_a);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoE;
    private javax.swing.JTextField NombreE;
    private javax.swing.JComboBox<String> comboBoxCursoE;
    private javax.swing.JTextField dniE;
    private javax.swing.JTextField emailE;
    private javax.swing.JTextField imagePath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel mostrarApellido;
    private javax.swing.JLabel mostrarNombre;
    private javax.swing.JTextField passwordE;
    private javax.swing.JTextField telefonoE;
    private javax.swing.JTextField tutorAE;
    private javax.swing.JTextField tutorNE;
    private javax.swing.JTextField usuarioE;
    // End of variables declaration//GEN-END:variables
}
