package ventanas;

import ConexionBD.BD;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class HomeProfesor1 extends javax.swing.JFrame {

    /**
     * Creates new form HomeEstudiante
     */
    BD con;
    ResultSet result;
    Icon message = new ImageIcon(getClass().getResource("/Resources/message.png"));

    public HomeProfesor1() {
        initComponents();
  con= new BD();
        con.Conectar();
        setLocationRelativeTo(null);
        fotoP.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mostrarNombre = new javax.swing.JLabel();
        mostrarApellido = new javax.swing.JLabel();
        NombreP = new javax.swing.JTextField();
        ApellidoP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cuilP = new javax.swing.JTextField();
        emailP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cargoCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        usuarioP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        materiasP = new javax.swing.JComboBox<>();
        cursoP = new javax.swing.JComboBox<>();
        fotoP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        passP = new javax.swing.JTextField();
        imgprofpath = new javax.swing.JLabel();
        imgprof = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        btnInstitucional = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Datos Personales del Profesor");

        mostrarNombre.setBackground(new java.awt.Color(255, 255, 255));
        mostrarNombre.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        mostrarNombre.setForeground(new java.awt.Color(102, 102, 102));
        mostrarNombre.setText("Nombre:");

        mostrarApellido.setBackground(new java.awt.Color(255, 255, 255));
        mostrarApellido.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        mostrarApellido.setForeground(new java.awt.Color(102, 102, 102));
        mostrarApellido.setText("Apellido:");

        NombreP.setEditable(false);
        NombreP.setBackground(new java.awt.Color(255, 255, 255));
        NombreP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        NombreP.setForeground(new java.awt.Color(20, 107, 109));
        NombreP.setBorder(null);
        NombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePActionPerformed(evt);
            }
        });

        ApellidoP.setEditable(false);
        ApellidoP.setBackground(new java.awt.Color(255, 255, 255));
        ApellidoP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ApellidoP.setForeground(new java.awt.Color(20, 107, 109));
        ApellidoP.setBorder(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("CUIL");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Correo electrónico");

        cuilP.setEditable(false);
        cuilP.setBackground(new java.awt.Color(255, 255, 255));
        cuilP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cuilP.setForeground(new java.awt.Color(20, 107, 109));
        cuilP.setBorder(null);
        cuilP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuilPActionPerformed(evt);
            }
        });

        emailP.setEditable(false);
        emailP.setBackground(new java.awt.Color(255, 255, 255));
        emailP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        emailP.setForeground(new java.awt.Color(20, 107, 109));
        emailP.setBorder(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Cargo");

        cargoCombo.setBackground(new java.awt.Color(255, 255, 255));
        cargoCombo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cargoCombo.setForeground(new java.awt.Color(20, 107, 109));
        cargoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planta Permanente", "Suplente" }));
        cargoCombo.setBorder(null);
        cargoCombo.setEnabled(false);
        cargoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoComboActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Nombre de usuario");

        usuarioP.setEditable(false);
        usuarioP.setBackground(new java.awt.Color(255, 255, 255));
        usuarioP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        usuarioP.setForeground(new java.awt.Color(20, 107, 109));
        usuarioP.setBorder(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Telefono");

        telefP.setEditable(false);
        telefP.setBackground(new java.awt.Color(255, 255, 255));
        telefP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        telefP.setForeground(new java.awt.Color(20, 107, 109));
        telefP.setBorder(null);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Materias");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Curso");

        materiasP.setBackground(new java.awt.Color(255, 255, 255));
        materiasP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        materiasP.setForeground(new java.awt.Color(20, 107, 109));
        materiasP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemática", "Estadística", "Sistemas de Procesamiento de Datos", "Arquitectura y Sistemas Operativos", "Metodología de la Investigación", "Legislacion" }));
        materiasP.setBorder(null);
        materiasP.setEnabled(false);

        cursoP.setBackground(new java.awt.Color(255, 255, 255));
        cursoP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cursoP.setForeground(new java.awt.Color(20, 107, 109));
        cursoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "201", "202", "203" }));
        cursoP.setBorder(null);
        cursoP.setEnabled(false);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Contraseña");

        passP.setEditable(false);
        passP.setBackground(new java.awt.Color(255, 255, 255));
        passP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        passP.setForeground(new java.awt.Color(20, 107, 109));
        passP.setBorder(null);

        imgprofpath.setToolTipText("");

        imgprof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/briefcase1.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostrarNombre)
                    .addComponent(mostrarApellido)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioP)
                    .addComponent(passP)
                    .addComponent(NombreP)
                    .addComponent(ApellidoP)
                    .addComponent(cuilP)
                    .addComponent(telefP, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailP, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cursoP, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materiasP, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgprofpath, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgprof, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(fotoP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)))
                .addComponent(imgprofpath)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgprof, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 26, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(usuarioP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(passP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mostrarNombre)
                                    .addComponent(NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mostrarApellido)
                                    .addComponent(ApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cuilP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(fotoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telefP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cargoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(materiasP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );

        jPanel7.setBackground(new java.awt.Color(229, 241, 241));

        jButton15.setBackground(new java.awt.Color(102, 175, 175));
        jButton15.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/teacher.png"))); // NOI18N
        jButton15.setText("Perfil");

        jButton16.setBackground(new java.awt.Color(229, 241, 241));
        jButton16.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        jButton16.setText("Modificar perfil");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(229, 241, 241));
        jButton17.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lupa.png"))); // NOI18N
        jButton17.setText("Consultas");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(102, 175, 175));
        jButton18.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/salir.png"))); // NOI18N
        jButton18.setText("Salir");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        btnInstitucional.setBackground(new java.awt.Color(229, 241, 241));
        btnInstitucional.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnInstitucional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/esc1.png"))); // NOI18N
        btnInstitucional.setText("Institucional");
        btnInstitucional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstitucionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInstitucional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton15)
                .addGap(39, 39, 39)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton17)
                .addGap(34, 34, 34)
                .addComponent(btnInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(jButton18)
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuilPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuilPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuilPActionPerformed

    private void cargoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoComboActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String ctr = passP.getText();

        Map<String, String> dataP = new HashMap<>();
        dataP.put("Key", ctr);

        EditProfesor ep = new EditProfesor(dataP);
        ep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String p_contrasenia = passP.getText();
        String p_curso = (String) cursoP.getSelectedItem();
        String p_cuil = cuilP.getText();

        Map<String, String> dataC = new HashMap<>();
        dataC.put("Key", p_contrasenia);
        dataC.put("p_curso", p_curso);
        dataC.put("p_cuil", p_cuil);

        ConsultasProfesores cp = new ConsultasProfesores(dataC);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        JOptionPane.showMessageDialog(null, "Has cerrado sesión.",
                "¡Éxito!", JOptionPane.INFORMATION_MESSAGE, message);
        VentanaInicio vi = new VentanaInicio();
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void NombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePActionPerformed

    private void btnInstitucionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstitucionalActionPerformed
        String c= passP.getText();
        Map<String, String> dataI= new HashMap<>();
        dataI.put("Key", c);
        InstitucionalEstudiante ie= new InstitucionalEstudiante(dataI);
        ie.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInstitucionalActionPerformed

    public void setUsuario(String u) {
        usuarioP.setText(u);
    }

    public void setPassword(String p) {

        passP.setText(p);
    }

    public void setNombre(String n) {
        NombreP.setText(n);
    }

    public void setApellido(String a) {
        ApellidoP.setText(a);
    }

    public void setCuil(String c) {
        cuilP.setText(c);
    }

    public void setTelefono(String t) {
        telefP.setText(t);
    }

    public void setEmail(String e) {
        emailP.setText(e);
    }

    public void setCargo(String val) {
        cargoCombo.setSelectedItem(val);
    }

    public void setMaterias(String m) {
        materiasP.setSelectedItem(m);
    }

    public void setCurso(String curso) {
        cursoP.setSelectedItem(curso);
    }

    public void setFoto(String imgpath) {
//          
        imgprofpath.setText(imgpath);
        ImageIcon MyImage = new ImageIcon(imgpath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(imgprof.getWidth(), imgprof.getHeight(), Image.SCALE_SMOOTH);
        imgprof.setIcon(new ImageIcon(newImage));
        imgprof.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoP;
    private javax.swing.JTextField NombreP;
    private javax.swing.JButton btnInstitucional;
    private javax.swing.JComboBox<String> cargoCombo;
    private javax.swing.JTextField cuilP;
    private javax.swing.JComboBox<String> cursoP;
    private javax.swing.JTextField emailP;
    private javax.swing.JTextField fotoP;
    private javax.swing.JLabel imgprof;
    private javax.swing.JLabel imgprofpath;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> materiasP;
    private javax.swing.JLabel mostrarApellido;
    private javax.swing.JLabel mostrarNombre;
    private javax.swing.JTextField passP;
    private javax.swing.JTextField telefP;
    private javax.swing.JTextField usuarioP;
    // End of variables declaration//GEN-END:variables

}
