package ventanas;

import ConexionBD.BD;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class HomeProfesor extends javax.swing.JFrame {

    /**
     * Creates new form HomeEstudiante
     */
    BD con;
    ResultSet result;
    Icon message = new ImageIcon(getClass().getResource("/Resources/message.png"));

    public HomeProfesor(Map<String, String> data) {
        initComponents();
        con = new BD();
        con.Conectar();

        String pass = data.get("Key");

        try {
            result = con.ConsultaProf(pass);
            while (result.next()) {
                usuarioP.setText(result.getString("U_Nbre"));
                NombreP.setText(result.getString("P_Nbre"));
                passP.setText(result.getString("U_Key"));
                ApellidoP.setText(result.getString("P_Apell"));
                cuilP.setText(result.getString("P_CUIL"));
                telefP.setText(result.getString("P_Tel"));
                fotoP.setText(result.getString("P_Foto"));
                emailP.setText(result.getString("P_Email"));
                cargoCombo.setSelectedItem(result.getString("P_Cond"));
                cursoP.setSelectedItem(result.getString("M_Curso"));
                materiasP.setSelectedItem(result.getString("M_Nbre"));

            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        fotoP.setVisible(false);
        imgprofpath.setVisible(false);
        String imgpath= fotoP.getText();
        setFoto(imgpath);
        setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mostrarNombre = new javax.swing.JLabel();
        mostrarApellido = new javax.swing.JLabel();
        NombreP = new javax.swing.JTextField();
        ApellidoP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cuilP = new javax.swing.JTextField();
        emailP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cargoCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        usuarioP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telefP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        materiasP = new javax.swing.JComboBox<>();
        cursoP = new javax.swing.JComboBox<>();
        fotoP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        passP = new javax.swing.JTextField();
        imgprofpath = new javax.swing.JLabel();
        imgprof = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botonModificarPerfil = new javax.swing.JButton();
        botonConsultas = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnInstitucional = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Datos Personales del Profesor");

        mostrarNombre.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        mostrarNombre.setForeground(new java.awt.Color(102, 102, 102));
        mostrarNombre.setText("Nombre:");

        mostrarApellido.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        mostrarApellido.setForeground(new java.awt.Color(102, 102, 102));
        mostrarApellido.setText("Apellido:");

        NombreP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        NombreP.setForeground(new java.awt.Color(20, 107, 109));
        NombreP.setBorder(null);

        ApellidoP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ApellidoP.setForeground(new java.awt.Color(20, 107, 109));
        ApellidoP.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("CUIL");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Correo electrónico");

        cuilP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cuilP.setForeground(new java.awt.Color(20, 107, 109));
        cuilP.setBorder(null);
        cuilP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuilPActionPerformed(evt);
            }
        });

        emailP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        emailP.setForeground(new java.awt.Color(20, 107, 109));
        emailP.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Cargo");

        cargoCombo.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cargoCombo.setForeground(new java.awt.Color(20, 107, 109));
        cargoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planta Permanente", "Suplente" }));
        cargoCombo.setEnabled(false);
        cargoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoComboActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Usuario");

        usuarioP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        usuarioP.setForeground(new java.awt.Color(20, 107, 109));
        usuarioP.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Teléfono");

        telefP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        telefP.setForeground(new java.awt.Color(20, 107, 109));
        telefP.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Materias");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Cursos");

        materiasP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        materiasP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemática", "Estadística", "Sistemas de Procesamiento de Datos", "Arquitectura y Sistemas Operativos", "Metodología de la Investigación", "Legislacion" }));

        cursoP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cursoP.setForeground(new java.awt.Color(20, 107, 109));
        cursoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "201", "202", "203" }));
        cursoP.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Contraseña");

        passP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        passP.setForeground(new java.awt.Color(20, 107, 109));
        passP.setBorder(null);
        passP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPActionPerformed(evt);
            }
        });

        imgprofpath.setToolTipText("");

        imgprof.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/briefcase1.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostrarNombre)
                            .addComponent(mostrarApellido)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fotoP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imgprofpath, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(passP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usuarioP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cuilP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgprof, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailP, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cursoP, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(materiasP, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(usuarioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(imgprofpath)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mostrarNombre)
                            .addComponent(NombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mostrarApellido)
                            .addComponent(ApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cuilP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(telefP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(imgprof, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fotoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(emailP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cursoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(materiasP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel3.setBackground(new java.awt.Color(229, 241, 241));

        jButton1.setBackground(new java.awt.Color(102, 175, 175));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/teacher.png"))); // NOI18N
        jButton1.setText("Perfil");

        botonModificarPerfil.setBackground(new java.awt.Color(229, 241, 241));
        botonModificarPerfil.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        botonModificarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit.png"))); // NOI18N
        botonModificarPerfil.setText("Modificar perfil");
        botonModificarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPerfilActionPerformed(evt);
            }
        });

        botonConsultas.setBackground(new java.awt.Color(229, 241, 241));
        botonConsultas.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        botonConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/lupa.png"))); // NOI18N
        botonConsultas.setText("Consultas");
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 175, 175));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/salir.png"))); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnInstitucional.setBackground(new java.awt.Color(229, 241, 241));
        btnInstitucional.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        btnInstitucional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/esc1.png"))); // NOI18N
        btnInstitucional.setText("Institucional");
        btnInstitucional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstitucionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInstitucional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(36, 36, 36)
                .addComponent(botonModificarPerfil)
                .addGap(40, 40, 40)
                .addComponent(botonConsultas)
                .addGap(29, 29, 29)
                .addComponent(btnInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
        String p_contrasenia = passP.getText();
        String p_curso = (String) cursoP.getSelectedItem();
        String p_cuil = cuilP.getText();
        
        Map<String, String> dataC = new HashMap<>();
        dataC.put("Key", p_contrasenia);
        dataC.put("p_curso", p_curso);
        dataC.put("p_cuil", p_cuil);

        ConsultasProfesores cp = new ConsultasProfesores(dataC);
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonConsultasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JOptionPane.showMessageDialog(null, "Has cerrado sesión.",
                "¡Éxito!", JOptionPane.INFORMATION_MESSAGE, message);
        VentanaInicio vi = new VentanaInicio();
        vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void botonModificarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPerfilActionPerformed
        String ctr = passP.getText();

        Map<String, String> dataP = new HashMap<>();
        dataP.put("Key", ctr);

        EditProfesor ep = new EditProfesor(dataP);
        ep.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonModificarPerfilActionPerformed

    private void passPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPActionPerformed

    private void cargoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoComboActionPerformed

    private void cuilPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuilPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuilPActionPerformed

    private void btnInstitucionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstitucionalActionPerformed
        String c= passP.getText();
        Map<String, String> dataI= new HashMap<>();
        dataI.put("Key", c);
        InstitucionalDocentes id= new InstitucionalDocentes(dataI);
        id.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInstitucionalActionPerformed

    public void setUsuario(String u) {
        usuarioP.setText(u);
    }

    public void setPassword(String p) {

        passP.setText(p);
    }

    public void setNombre(String n) {
        NombreP.setText(n);
    }

    public void setApellido(String a) {
        ApellidoP.setText(a);
    }

    public void setCuil(String c) {
        cuilP.setText(c);
    }

    public void setTelefono(String t) {
        telefP.setText(t);
    }

    public void setEmail(String e) {
        emailP.setText(e);
    }

    public void setCargo(String val) {
        cargoCombo.setSelectedItem(val);
    }

    public void setMaterias(String m) {
        materiasP.setSelectedItem(m);
    }

    public void setCurso(String curso) {
        cursoP.setSelectedItem(curso);
    }

    public void setFoto(String imgpath) {
//          
        imgprofpath.setText(imgpath);
        ImageIcon MyImage = new ImageIcon(imgpath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(imgprof.getWidth(), imgprof.getHeight(), Image.SCALE_SMOOTH);
        imgprof.setIcon(new ImageIcon(newImage));
        imgprof.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoP;
    private javax.swing.JTextField NombreP;
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonModificarPerfil;
    private javax.swing.JButton btnInstitucional;
    private javax.swing.JComboBox<String> cargoCombo;
    private javax.swing.JTextField cuilP;
    private javax.swing.JComboBox<String> cursoP;
    private javax.swing.JTextField emailP;
    private javax.swing.JTextField fotoP;
    private javax.swing.JLabel imgprof;
    private javax.swing.JLabel imgprofpath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> materiasP;
    private javax.swing.JLabel mostrarApellido;
    private javax.swing.JLabel mostrarNombre;
    private javax.swing.JTextField passP;
    private javax.swing.JTextField telefP;
    private javax.swing.JTextField usuarioP;
    // End of variables declaration//GEN-END:variables

}
