package ventanas;


import ventanas.RegistroProfesor;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import modelo.Usuario;


public class RegistroPanel extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPanel
     */
        ArrayList<Usuario> usuarios = new ArrayList<>();

    public RegistroPanel() {
        initComponents();  
        
         Image imgEstud = new ImageIcon(getClass().getResource("/Resources/panelestudiante.png")).getImage();

        Image imgScale = imgEstud.getScaledInstance(imgpanel.getWidth(), imgpanel.getHeight(),
                Image.SCALE_SMOOTH);
        imgpanel.setIcon(new ImageIcon(imgScale));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoUsuarioRegistro = new javax.swing.JComboBox<>();
        botonIniciarRegistro = new javax.swing.JButton();
        imgpanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escuela N ° 178");

        jPanel2.setBackground(new java.awt.Color(244, 246, 246));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Seleccione tipo de usuario a registrar");

        tipoUsuarioRegistro.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        tipoUsuarioRegistro.setForeground(new java.awt.Color(102, 102, 102));
        tipoUsuarioRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor" }));
        tipoUsuarioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoUsuarioRegistroActionPerformed(evt);
            }
        });

        botonIniciarRegistro.setBackground(new java.awt.Color(0, 122, 122));
        botonIniciarRegistro.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        botonIniciarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botonIniciarRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/edit2.png"))); // NOI18N
        botonIniciarRegistro.setText("Iniciar registro");
        botonIniciarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonIniciarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(imgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(tipoUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonIniciarRegistro)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(85, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonIniciarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarRegistroActionPerformed
        RegistroEstudiante ventEst = new RegistroEstudiante();
        RegistroProfesor ventProf = new RegistroProfesor();
        if (tipoUsuarioRegistro.getSelectedItem() == "Estudiante") {
             
            ventEst.setVisible(true);
            this.dispose();
        } else {
             
            ventProf.setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_botonIniciarRegistroActionPerformed

    private void tipoUsuarioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoUsuarioRegistroActionPerformed
        if(tipoUsuarioRegistro.getSelectedItem()=="Profesor"){
             Image imgDocente = new ImageIcon(getClass().getResource("/Resources/paneldocente.png")).getImage();

        Image imgScale = imgDocente.getScaledInstance(imgpanel.getWidth(), imgpanel.getHeight(),
                Image.SCALE_SMOOTH);
        imgpanel.setIcon(new ImageIcon(imgScale)); 
        }else{
            Image imgEstud = new ImageIcon(getClass().getResource("/Resources/panelestudiante.png")).getImage();

        Image imgScale = imgEstud.getScaledInstance(imgpanel.getWidth(), imgpanel.getHeight(),
                Image.SCALE_SMOOTH);
        imgpanel.setIcon(new ImageIcon(imgScale));
        }
    }//GEN-LAST:event_tipoUsuarioRegistroActionPerformed

    public void setUsuario(String u) {
        if (u.equals("Estudiante")) {
            tipoUsuarioRegistro.setSelectedItem("Estudiante");
        } else {
            tipoUsuarioRegistro.setSelectedItem("Profesor");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIniciarRegistro;
    private javax.swing.JLabel imgpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> tipoUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
