package ventanas;

import ConexionBD.BD;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Materia;
import modelo.Profesor;
import modelo.Usuario;

public class RegistroProfesor extends javax.swing.JFrame {

    ArrayList<Profesor> docentes = new ArrayList<>();
    Icon message = new ImageIcon(getClass().getResource("/Resources/message.png"));
File f = null;
    String path = null;
    /**
     * Creates new form RegistroEstudiante
     */
    BD con;

    public RegistroProfesor() {
        initComponents();
        con = new BD();

        con.Conectar();
        rolProf.setVisible(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usuarioProfTxt = new javax.swing.JTextField();
        nombreProfTxt = new javax.swing.JTextField();
        passwordProfTxt = new javax.swing.JPasswordField();
        apellidoProfxt = new javax.swing.JTextField();
        cuilProfTxt = new javax.swing.JTextField();
        fotoProf = new javax.swing.JTextField();
        emailProfTxt = new javax.swing.JTextField();
        ListaCargoP = new javax.swing.JComboBox<>();
        rolProf = new javax.swing.JComboBox<>();
        combocursoProf = new javax.swing.JComboBox<>();
        comboMaterias = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        telefP = new javax.swing.JTextField();
        imagenProfe = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();
        btnBuscarFoto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Registro de Profesor");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nombre de usuario");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Contraseña");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nombre");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Apellido");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("CUIL");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Foto");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Correo Electrónico");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Cargo");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Materias a cargo");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Cursos");

        jButton1.setBackground(new java.awt.Color(0, 122, 122));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/ok1.png"))); // NOI18N
        jButton1.setText("Cargar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        usuarioProfTxt.setBackground(new java.awt.Color(255, 255, 255));
        usuarioProfTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        usuarioProfTxt.setForeground(new java.awt.Color(20, 107, 109));
        usuarioProfTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 107, 109)));

        nombreProfTxt.setBackground(new java.awt.Color(255, 255, 255));
        nombreProfTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nombreProfTxt.setForeground(new java.awt.Color(20, 107, 109));
        nombreProfTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 107, 109)));
        nombreProfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProfTxtActionPerformed(evt);
            }
        });

        passwordProfTxt.setBackground(new java.awt.Color(255, 255, 255));
        passwordProfTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        passwordProfTxt.setForeground(new java.awt.Color(20, 107, 109));
        passwordProfTxt.setText("password");
        passwordProfTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 107, 109)));

        apellidoProfxt.setBackground(new java.awt.Color(255, 255, 255));
        apellidoProfxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        apellidoProfxt.setForeground(new java.awt.Color(20, 107, 109));
        apellidoProfxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 107, 109)));

        cuilProfTxt.setBackground(new java.awt.Color(255, 255, 255));
        cuilProfTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        cuilProfTxt.setForeground(new java.awt.Color(20, 107, 109));
        cuilProfTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 107, 109)));
        cuilProfTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuilProfTxtActionPerformed(evt);
            }
        });

        fotoProf.setBackground(new java.awt.Color(255, 255, 255));
        fotoProf.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        fotoProf.setForeground(new java.awt.Color(20, 107, 109));
        fotoProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 107, 109)));
        fotoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoProfActionPerformed(evt);
            }
        });

        emailProfTxt.setBackground(new java.awt.Color(255, 255, 255));
        emailProfTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        emailProfTxt.setForeground(new java.awt.Color(20, 107, 109));
        emailProfTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 107, 109)));

        ListaCargoP.setBackground(new java.awt.Color(255, 255, 255));
        ListaCargoP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ListaCargoP.setForeground(new java.awt.Color(20, 107, 109));
        ListaCargoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planta Permanente", "Suplente" }));
        ListaCargoP.setBorder(null);
        ListaCargoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaCargoPActionPerformed(evt);
            }
        });

        rolProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "profesor" }));

        combocursoProf.setBackground(new java.awt.Color(255, 255, 255));
        combocursoProf.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        combocursoProf.setForeground(new java.awt.Color(20, 107, 109));
        combocursoProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "201", "202", "203" }));
        combocursoProf.setBorder(null);

        comboMaterias.setBackground(new java.awt.Color(255, 255, 255));
        comboMaterias.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        comboMaterias.setForeground(new java.awt.Color(20, 107, 109));
        comboMaterias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemática", "Estadística", "Sistemas de Procesamiento de Datos", "Arquitectura y Sistemas Operativos", "Metodología de la Investigación", "Legislacion" }));
        comboMaterias.setBorder(null);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Telefono");

        telefP.setBackground(new java.awt.Color(255, 255, 255));
        telefP.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        telefP.setForeground(new java.awt.Color(20, 107, 109));
        telefP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 107, 109)));

        imagelabel.setText("jLabel13");
        imagelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        btnBuscarFoto.setBackground(new java.awt.Color(0, 122, 122));
        btnBuscarFoto.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnBuscarFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarFoto.setText("Buscar Foto");
        btnBuscarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuarioProfTxt)
                                    .addComponent(passwordProfTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(nombreProfTxt)
                                    .addComponent(apellidoProfxt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ListaCargoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combocursoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rolProf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefP, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emailProfTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cuilProfTxt)
                                        .addGap(33, 33, 33))
                                    .addComponent(fotoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(106, 106, 106)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imagenProfe, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenProfe, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usuarioProfTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordProfTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombreProfTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(apellidoProfxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuilProfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailProfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(fotoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnBuscarFoto))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12)
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(telefP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ListaCargoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(combocursoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(comboMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rolProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(229, 241, 241));
        jPanel3.setPreferredSize(new java.awt.Dimension(173, 579));

        jButton5.setBackground(new java.awt.Color(102, 175, 175));
        jButton5.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/crear.png"))); // NOI18N
        jButton5.setText("Registro");

        jButton6.setBackground(new java.awt.Color(229, 241, 241));
        jButton6.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/esc1.png"))); // NOI18N
        jButton6.setText("Institucional");

        jButton7.setBackground(new java.awt.Color(102, 175, 175));
        jButton7.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/salir.png"))); // NOI18N
        jButton7.setText("Salir");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton5)
                .addGap(39, 39, 39)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fotoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fotoProfActionPerformed

    private void nombreProfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProfTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String usuario = usuarioProfTxt.getText();
        String pass = String.valueOf(passwordProfTxt.getPassword());
        String rol = (String) rolProf.getSelectedItem();
        Usuario u = new Usuario(usuario, pass, rol);

        con.CrearUsuario(u);

        String nombreProf = nombreProfTxt.getText();
        String apellidoProf = apellidoProfxt.getText();
        Long cuil = Long.valueOf(cuilProfTxt.getText());
        String telef = telefP.getText();
        String emailProf = emailProfTxt.getText();
        String foto = fotoProf.getText();

        String cargo = (String) ListaCargoP.getSelectedItem();
        String p_key = u.getPassword();
        Profesor prof = new Profesor(cuil, nombreProf,
                apellidoProf, telef, emailProf, foto, cargo, p_key);

        docentes.add(prof);
        System.out.println(prof);
        con.CrearProfesor(prof);

        JOptionPane.showMessageDialog(rootPane, "Profesor creado exitosamente",
                "Registro exitoso", JOptionPane.PLAIN_MESSAGE);

        String NbreMateria = (String) comboMaterias.getSelectedItem();
        int cursoP = Integer.parseInt((String) combocursoProf.getSelectedItem());
        Materia m = new Materia(NbreMateria, cursoP);
        con.crearMateria(m);
        con.crearProfMateria(m, prof);

        HomeProfesor1 home = new HomeProfesor1();
        home.setUsuario(usuarioProfTxt.getText());
        home.setNombre(nombreProfTxt.getText());
        home.setApellido(apellidoProfxt.getText());
        home.setCuil(cuilProfTxt.getText());
        home.setTelefono(telefP.getText());
        home.setEmail(emailProfTxt.getText());
        home.setCargo(ListaCargoP.getSelectedItem().toString());
        home.setCurso((String) combocursoProf.getSelectedItem());
        home.setFoto(fotoProf.getText());
        home.setMaterias((String) comboMaterias.getSelectedItem());
        home.setPassword(pass);
        home.setVisible(true);
        this.dispose();
        home.setVisible(true);    }//GEN-LAST:event_jButton1ActionPerformed

    private void ListaCargoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaCargoPActionPerformed

    }//GEN-LAST:event_ListaCargoPActionPerformed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        JOptionPane.showMessageDialog(null, "Has cerrado sesión.",
                "¡Vuelve pronto!", JOptionPane.INFORMATION_MESSAGE, message);
        VentanaInicio vent = new VentanaInicio();
        vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7MousePressed

    private void cuilProfTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuilProfTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuilProfTxtActionPerformed

    private void btnBuscarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter fnwf = new FileNameExtensionFilter("PNG JPG AND JPEG", "png", "jpeg", "jpg");
        fileChooser.addChoosableFileFilter(fnwf);
        int load = fileChooser.showOpenDialog(null);

        if (load == fileChooser.APPROVE_OPTION) {
            f = fileChooser.getSelectedFile();

            path = f.getAbsolutePath();

            fotoProf.setText(path);
            ImageIcon ii = new ImageIcon(path);
            Image img = ii.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            imagelabel.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_btnBuscarFotoActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaCargoP;
    private javax.swing.JTextField apellidoProfxt;
    private javax.swing.JButton btnBuscarFoto;
    private javax.swing.JComboBox<String> comboMaterias;
    private javax.swing.JComboBox<String> combocursoProf;
    private javax.swing.JTextField cuilProfTxt;
    private javax.swing.JTextField emailProfTxt;
    private javax.swing.JTextField fotoProf;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JLabel imagenProfe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nombreProfTxt;
    private javax.swing.JPasswordField passwordProfTxt;
    private javax.swing.JComboBox<String> rolProf;
    private javax.swing.JTextField telefP;
    private javax.swing.JTextField usuarioProfTxt;
    // End of variables declaration//GEN-END:variables
}
