package ventanas;


import ventanas.HomeEstudiante;
import ConexionBD.BD;
import java.awt.Cursor;
import java.awt.Image;
import java.sql.*;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import modelo.Estudiante;
import modelo.Profesor;

public class VentanaInicio extends javax.swing.JFrame {
  

    BD con;
    ResultSet result;
    PreparedStatement ps = null;
    ArrayList<Profesor> profesores = new ArrayList<>();
    HashMap<String, String> ingreso;
            Icon ok= new ImageIcon(getClass().getResource("/Resources/ok2.png"));
    Icon icon= new ImageIcon(getClass().getResource("/Resources/error.png"));
String al="estudiante";

    /**
     * Creates new form Ventana
     */
    public VentanaInicio() {
        initComponents();
        con = new BD();
        con.Conectar();

       
        
        Image imgEscInicio = new ImageIcon(getClass().getResource("/Resources/login.png")).getImage();

        Image imgScale = imgEscInicio.getScaledInstance(imagenEscuela.getWidth(), imagenEscuela.getHeight(),
                Image.SCALE_SMOOTH);
        imagenEscuela.setIcon(new ImageIcon(imgScale));
        setLocationRelativeTo(null);
    }



//    public void Loguearse(String user, String pass) {
//
//        //Verificar que el usuario exista
//        if (ingreso.get(user).equals(pass)) {
//            JOptionPane.showMessageDialog(null, "Login Correcto",
//                    "¡Éxito!", JOptionPane.INFORMATION_MESSAGE, ok);
//
//            HomeEstudiante he = new HomeEstudiante();
//            he.setVisible(true);
//        } else {
//            JOptionPane.showMessageDialog(null, "Login incorrecto");
//        }
//    }
    private void iniciarsesion(String user, String pass){
     
       con.iniciarSesion(user, pass);
     
             this.dispose();
        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        botonIngreso = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonRegistro = new javax.swing.JButton();
        imagenEscuela = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mostrarPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escuela N ° 178");
        setIconImage(new ImageIcon(getClass().getResource
            ("/Resources/e1.jpg")).getImage());
    setResizable(false);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 28)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(102, 102, 102));
    jLabel1.setText("Ingreso a Sistema Escolar");

    jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(102, 102, 102));
    jLabel2.setText("Introduzca nombre de usuario");

    jLabel3.setBackground(new java.awt.Color(255, 255, 255));
    jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(102, 102, 102));
    jLabel3.setText("Introduzca contraseña");

    pass.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
    pass.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            passActionPerformed(evt);
        }
    });

    botonIngreso.setBackground(new java.awt.Color(0, 122, 122));
    botonIngreso.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
    botonIngreso.setForeground(new java.awt.Color(255, 255, 255));
    botonIngreso.setText("Ingresar");
    botonIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            botonIngresoMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            botonIngresoMouseExited(evt);
        }
    });
    botonIngreso.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonIngresoActionPerformed(evt);
        }
    });

    jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
    jLabel4.setForeground(new java.awt.Color(102, 102, 102));
    jLabel4.setText("¿Aún no tienes cuenta?");

    botonRegistro.setBackground(new java.awt.Color(255, 255, 255));
    botonRegistro.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
    botonRegistro.setForeground(new java.awt.Color(0, 153, 153));
    botonRegistro.setText("Regístrate");
    botonRegistro.setBorder(null);
    botonRegistro.setBorderPainted(false);
    botonRegistro.setContentAreaFilled(false);
    botonRegistro.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            botonRegistroStateChanged(evt);
        }
    });
    botonRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        public void mouseMoved(java.awt.event.MouseEvent evt) {
            botonRegistroMouseMoved(evt);
        }
    });
    botonRegistro.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonRegistroActionPerformed(evt);
        }
    });

    imagenEscuela.setBackground(new java.awt.Color(204, 255, 204));

    jLabel5.setBackground(new java.awt.Color(255, 255, 255));
    jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(60, 63, 65));
    jLabel5.setText("Desarrollado por Marianela Cilene Gamarra - Argentina Programa & UNSL - 2023");

    mostrarPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
    mostrarPass.setForeground(new java.awt.Color(102, 102, 102));
    mostrarPass.setText("Mostrar");
    mostrarPass.setBorder(null);
    mostrarPass.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            mostrarPassActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(64, 64, 64)
            .addComponent(imagenEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(94, 94, 94)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(botonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(botonIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(mostrarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(111, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(204, 204, 204))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jLabel1)
                    .addGap(34, 34, 34)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(mostrarPass)
                    .addGap(24, 24, 24)
                    .addComponent(botonIngreso)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonRegistro)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(44, Short.MAX_VALUE)
                    .addComponent(imagenEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)))
            .addComponent(jLabel5)
            .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 6, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        RegistroPanel reg = new RegistroPanel();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void botonRegistroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botonRegistroStateChanged

    }//GEN-LAST:event_botonRegistroStateChanged

    private void botonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoActionPerformed
        String usuario = user.getText();
        String contraseña = String.valueOf(pass.getPassword());
        iniciarsesion(usuario, contraseña);
    }//GEN-LAST:event_botonIngresoActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void botonRegistroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseMoved
        botonRegistro.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonRegistroMouseMoved

    private void botonIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresoMouseEntered
        botonIngreso.setBackground(new java.awt.Color(0, 122, 122));
    }//GEN-LAST:event_botonIngresoMouseEntered

    private void botonIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresoMouseExited
               botonIngreso.setBackground(new java.awt.Color(0, 122, 122));

    }//GEN-LAST:event_botonIngresoMouseExited

    private void mostrarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPassActionPerformed
       if( mostrarPass.isSelected()){
               pass.setEchoChar((char)0);
   } else {
      pass.setEchoChar('*');
   }
       
    }//GEN-LAST:event_mostrarPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngreso;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JLabel imagenEscuela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mostrarPass;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

}
